# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: h:/UserFiles/Desktop/OV7670_XY_ok1/OV7670_1/OV7670_1.srcs/sources_1/ip/DIV_32_32_2/DIV_32_32.xci
# IP: The module: 'DIV_32_32' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: h:/UserFiles/Desktop/OV7670_XY_ok1/OV7670_1/OV7670_1.srcs/sources_1/ip/DIV_32_32_2/DIV_32_32_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'DIV_32_32'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# IP: h:/UserFiles/Desktop/OV7670_XY_ok1/OV7670_1/OV7670_1.srcs/sources_1/ip/DIV_32_32_2/DIV_32_32.xci
# IP: The module: 'DIV_32_32' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: h:/UserFiles/Desktop/OV7670_XY_ok1/OV7670_1/OV7670_1.srcs/sources_1/ip/DIV_32_32_2/DIV_32_32_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'DIV_32_32'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
