# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir H:/Desktop/OV7670_XY_GREEN_YELLOW_1/OV7670_XY_ok1/OV7670_1/OV7670_1.cache/wt [current_project]
set_property parent.project_path H:/Desktop/OV7670_XY_GREEN_YELLOW_1/OV7670_XY_ok1/OV7670_1/OV7670_1.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
add_files -quiet H:/Desktop/OV7670_XY_GREEN_YELLOW_1/OV7670_XY_ok1/OV7670_1/OV7670_1.runs/clk_wiz_0_synth_1/clk_wiz_0.dcp
set_property used_in_implementation false [get_files H:/Desktop/OV7670_XY_GREEN_YELLOW_1/OV7670_XY_ok1/OV7670_1/OV7670_1.runs/clk_wiz_0_synth_1/clk_wiz_0.dcp]
add_files -quiet H:/Desktop/OV7670_XY_GREEN_YELLOW_1/OV7670_XY_ok1/OV7670_1/OV7670_1.runs/DIV_32_32_synth_1/DIV_32_32.dcp
set_property used_in_implementation false [get_files H:/Desktop/OV7670_XY_GREEN_YELLOW_1/OV7670_XY_ok1/OV7670_1/OV7670_1.runs/DIV_32_32_synth_1/DIV_32_32.dcp]
add_files -quiet H:/Desktop/OV7670_XY_GREEN_YELLOW_1/OV7670_XY_ok1/OV7670_1/OV7670_1.runs/blk_mem_gen_0_synth_1/blk_mem_gen_0.dcp
set_property used_in_implementation false [get_files H:/Desktop/OV7670_XY_GREEN_YELLOW_1/OV7670_XY_ok1/OV7670_1/OV7670_1.runs/blk_mem_gen_0_synth_1/blk_mem_gen_0.dcp]
read_verilog -library xil_defaultlib {
  H:/Desktop/OV7670_XY_GREEN_YELLOW_1/OV7670_XY_ok1/OV7670_1/OV7670_1.srcs/sources_1/new/cfg_reg.v
  H:/Desktop/OV7670_XY_GREEN_YELLOW_1/OV7670_XY_ok1/OV7670_1/OV7670_1.srcs/sources_1/new/SCCB_sender.v
  H:/Desktop/OV7670_XY_GREEN_YELLOW_1/OV7670_XY_ok1/OV7670_1/OV7670_1.srcs/sources_1/new/Motor_position_detect.v
  H:/Desktop/OV7670_XY_GREEN_YELLOW_1/OV7670_XY_ok1/OV7670_1/OV7670_1.srcs/sources_1/new/Moter_Y.v
  H:/Desktop/OV7670_XY_GREEN_YELLOW_1/OV7670_XY_ok1/OV7670_1/OV7670_1.srcs/sources_1/new/Moter_X.v
  H:/Desktop/OV7670_XY_GREEN_YELLOW_1/OV7670_XY_ok1/OV7670_1/OV7670_1.srcs/sources_1/new/Coordinate_calculate.v
  H:/Desktop/OV7670_XY_GREEN_YELLOW_1/OV7670_XY_ok1/OV7670_1/OV7670_1.srcs/sources_1/new/cfg_ov7670.v
  H:/Desktop/OV7670_XY_GREEN_YELLOW_1/OV7670_XY_ok1/OV7670_1/OV7670_1.srcs/sources_1/new/VGA.v
  H:/Desktop/OV7670_XY_GREEN_YELLOW_1/OV7670_XY_ok1/OV7670_1/OV7670_1.srcs/sources_1/new/DATA_processing.v
  H:/Desktop/OV7670_XY_GREEN_YELLOW_1/OV7670_XY_ok1/OV7670_1/OV7670_1.srcs/sources_1/new/ov7670_vga.v
}
read_xdc H:/Desktop/OV7670_XY_GREEN_YELLOW_1/OV7670_XY_ok1/OV7670_1/OV7670_1.srcs/constrs_1/new/ov7670_1.xdc
set_property used_in_implementation false [get_files H:/Desktop/OV7670_XY_GREEN_YELLOW_1/OV7670_XY_ok1/OV7670_1/OV7670_1.srcs/constrs_1/new/ov7670_1.xdc]

synth_design -top ov7670_vga -part xc7a35tcpg236-1
write_checkpoint -noxdef ov7670_vga.dcp
catch { report_utilization -file ov7670_vga_utilization_synth.rpt -pb ov7670_vga_utilization_synth.pb }
